spring:
  application:
    name: home_notifications
  mail:
    host: smtp.gmail.com
    port: 587
    username: username
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true

server:
  port: 8080