spring:
  application:
    name: home_notifications
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6000/notifications
    username: postgres
    password: postgres
  mail:
    host: smtp.gmail.com
    port: 587
    username: user
    password: pass
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

bot:
  token: token
  username: name

server:
  port: 8081